<a href="https://colab.research.google.com/github/Znixz/haidezlair/blob/main/Ibm_quantum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install qiskit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 85.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 83.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 4.0 MB/s eta 0:00:00


In [ ]:
!pip install sympy

In [ ]:
!pip install matplotlib

In [ ]:
!pip install pylatexenc

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 7.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pylatexenc: filename=pylatexenc-2.10-py3-none-any.whl size=136817 sha256=d190c9cb71d50ffc0a19925946f74db660557987e9f9aef7cbb2b9ab015f225c
  Stored in directory: /root/.cache/pip/wheels/06/3e/78/fa1588c1ae991bbfd814af2bcac6cef7a178beee1939180d46
Successfully built pylatexenc


In [ ]:
#"The following code loads this library,
#defines two column vectors, ket0 and ket1,
#corresponding to the qubit state vectors
#∣0⟩ and ∣1⟩, and then prints their average."#

import numpy as np

ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]])

print(ket0 / 2 + ket1 / 2)

[[0.5]
 [0.5]]


In [ ]:
import numpy as np
ket0 = np.array([[1] ,[0]])
ket1 = np.array([[0] ,[1]])

print(ket0/2 + ket1/2)

[[0.5]
 [0.5]]


In [ ]:
#"We can also use array to create matrices
#that can represent operations. "#

M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])
M = M1 / 2 + M2 / 2
print(M)

[[1.  0.5]
 [0.  0.5]]


In [ ]:
M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])
M = M1/2 + M2/2
print(M)

[[1.  0.5]
 [0.  0.5]]


In [ ]:
#'Matrix multiplication, including
#matrix-vector multiplication
#as a special case, can be
#performed using the @ operator.'#

ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]])
M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])
M = M1/2 + M2/2

print(M1 @ ket1)
print(M1 @ M2)
print(M @ M)

[[1]
 [0]]
[[1 1]
 [0 0]]
[[1.   0.75]
 [0.   0.25]]


One solution, for situations that demand something prettier, is to use thearray_to_latex function in Qiskit, from the qiskit.visualization module. Note that, in the code that follows, we're using Python's generic display function. In contrast, the specific behavior of print may depending on what is printed, such as it does for arrays defined by NumPy.

In [ ]:
print(ket0)

[[1]
 [0]]


In [ ]:
from qiskit.visualization import array_to_latex

display(array_to_latex(ket0))
print("\n")
display(array_to_latex(ket1))
print("\n")
display(array_to_latex(M1))
print("\n")
display(array_to_latex(M2))
print("\n")
display(array_to_latex(M))
print("\n")
display(array_to_latex(M1 @ ket1))
print("\n")
display(array_to_latex(M1 @ M2))
print("\n")
display(array_to_latex(M @ M))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [4]:
count = 5
if count > 0:
    count = 10
print(count)

10


In [2]:
#Using Statevector class
#from qiskit
#sqrt is imported from numpy
!pip install qiskit
from qiskit.quantum_info import Statevector
from numpy import sqrt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 62.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 94.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 4.9 MB/s eta 0:00:00


In [ ]:

from qiskit.quantum_info import Statevector
from numpy import sqrt

u = Statevector([1 / sqrt(2), 1 / sqrt(2)])
v = Statevector([(1 + 2.0j) / 3, -2 / 3])
w = Statevector([1 / 3, 2 / 3])

In [5]:
from qiskit.quantum_info import Statevector
from numpy import sqrt

u = Statevector([1/sqrt(2), 1/sqrt(2)])
v = Statevector([(1 + 2.0j)/3, - 2/3])
w = Statevector([1/3, 2/3])

#Statevector class include draw method
#for displaying Statevector in
#text, latex, and latex_source
#use print for latex_source
display(u.draw("text"))
display(u.draw("latex"))
print(u.draw("latex_source"))

[0.70710678+0.j,0.70710678+0.j]

<IPython.core.display.Latex object>

\frac{\sqrt{2}}{2} |0\rangle+\frac{\sqrt{2}}{2} |1\rangle


In [6]:
#Statevector also include is_valid method
#To check if a vector follows ||v||
display(u.is_valid())
display(v.is_valid())
display(w.is_valid())

True

True

False

In [15]:
outcome, state = v.measure()
print(f"Measured: {outcome}\nPost-measurement state:")
display(state.draw("latex"))

Measured: 0
Post-measurement state:


<IPython.core.display.Latex object>

In [21]:
outcome, state = v.measure()
print(outcome)
print(state)

display(state.draw("latex"))

0
Statevector([0.4472136+0.89442719j, 0.       +0.j        ],
            dims=(2,))


<IPython.core.display.Latex object>

In [14]:
#Simulating measurements using Statevector
#Measurement can be simulated using
# measure method from the Statevector class


v = Statevector([(1 + 2.0j)/3, - 2/3])

outcome, state = v.measure()
print(f"Measured: {outcome}\nPost-measurement state:")
display(state.draw("latex"))

Measured: 1
Post-measurement state:


<IPython.core.display.Latex object>